import type { ProfileData } from '../api/chat';

interface Props {
  profile: ProfileData;
}

const SECTION_META = [
  {
    key: 'humanEdge' as const,
    title: 'Your Human Edge',
    icon: '✦',
    accent: 'accent-purple',
  },
  {
    key: 'superpower' as const,
    title: 'Your Superpower',
    icon: '⚡',
    accent: 'accent-blue',
  },
  {
    key: 'blindSpot' as const,
    title: 'Your Blind Spot',
    icon: '◐',
    accent: 'accent-amber',
  },
  {
    key: 'nextMove' as const,
    title: 'Your Next Move',
    icon: '→',
    accent: 'accent-green',
  },
];

export default function ResultsDisplay({ profile }: Props) {
  return (
    <div className="results">
      <div className="results-header">
        <h1 className="results-title">Your Human Edge Profile</h1>
        <p className="results-subtitle">
          Generated by the Expanded Coach — powered by Expanded Future
        </p>
      </div>

      <div className="results-grid">
        {SECTION_META.map(({ key, title, icon, accent }) => (
          <div key={key} className={`results-card ${accent}`}>
            <div className="results-card-header">
              <span className="results-card-icon">{icon}</span>
              <h2 className="results-card-title">{title}</h2>
            </div>
            <div className="results-card-body">
              {profile[key].split('\n').map((line, i) =>
                line.trim() ? <p key={i}>{line}</p> : null
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="results-footer">
        <p className="results-cta">
          Screenshot &amp; share your profile — tag{' '}
          <strong>@ExpandedFuture</strong>
        </p>
        <button
          className="btn-primary"
          onClick={() => window.location.reload()}
        >
          Start again
        </button>
      </div>
    </div>
  );
}
